# cluster-config.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-east-1
  version: "1.32"

autoModeConfig:
  enabled: false

managedNodeGroups:
  - name: my-nodes
    instanceType: t3.small
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: false