apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-service
spec:
  # The 'selector' must match the labels of the Pods (from nginx-deployment.yaml)
  selector:
    app: nginx
  # LoadBalancer exposes the Service via a Cloud Provider's external load balancer,
  # which automatically assigns an EXTERNAL-IP.
  type: LoadBalancer
  ports:
    # Port 80 is the Service port (internal cluster communication)
    - port: 80
      # TargetPort 80 is the port the Nginx container listens on
      targetPort: 80
